# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SPI_INT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.POT1 = QtWidgets.QLabel(self.centralwidget)
        self.POT1.setGeometry(QtCore.QRect(160, 260, 131, 91))
        self.POT1.setObjectName("POT1")
        self.POT2 = QtWidgets.QLabel(self.centralwidget)
        self.POT2.setGeometry(QtCore.QRect(490, 290, 91, 41))
        self.POT2.setObjectName("POT2")
        self.POT1_P = QtWidgets.QProgressBar(self.centralwidget)
        self.POT1_P.setGeometry(QtCore.QRect(160, 350, 118, 23))
        self.POT1_P.setProperty("value", 24)
        self.POT1_P.setObjectName("POT1_P")
        self.POT2_P = QtWidgets.QProgressBar(self.centralwidget)
        self.POT2_P.setGeometry(QtCore.QRect(480, 350, 118, 23))
        self.POT2_P.setProperty("value", 24)
        self.POT2_P.setObjectName("POT2_P")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.POT1.setText(_translate("MainWindow", "TextLabel"))
        self.POT2.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
